/*
 * TherapyTemplate.h
 *
 *  Created on: Dec 12, 2025
 *      Author: Roberto.Sanchez
 */

#ifndef APPLICATION_USER_TOUCHGFX_GUI_INCLUDE_GUI_MODEL_THERAPYTEMPLATES_HPP_
#define APPLICATION_USER_TOUCHGFX_GUI_INCLUDE_GUI_MODEL_THERAPYTEMPLATES_HPP_


#include "BitmapDatabase.hpp"

extern "C" FSM_O3_OPERATION_T GLB_fsm_o3;

void setMaxFlow(void);
void setMaxTime(void);

const THERAPY_CTX therapyTemplates[] = {
    /*[SYRINGE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_JERINGA_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              950,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0,  0,  0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 0,  0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1,  30, 1, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "ug/Nml" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_TIME },
        /*secondSelectionVisible*/ { false, false, false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[SYRINGE_AUTO_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_JERINGAAUTO_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              950,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0,  0,  0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 0,  0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1,  30, 1, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "ug/Nml" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW , TTV_TIME },
        /*secondSelectionVisible*/ { false, false, false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[SYRINGE_MANUAL_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_JERINGAMANUAL_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              950,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0,  0,  0,  0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 0,  0,  0, 0, 0, 0, 0 },
        /*defValue*/               { 1,  30, 10, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,  0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "ug/Nml" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_TIME },
        /*secondSelectionVisible*/ { false, false, false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[CONTINUOUS_MODE]*/ {
        /*stepsNum*/                 3,
        /*mainIcon*/                 BITMAP_CONTINUO_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_FLOW_00_ID, BITMAP_TIME_00_ID },
        /*minValue*/               { 1,  10, 1,  0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 50, 20, 0, 0, 0, 0, 0 },
        /*defValue*/               { 40, 22, 2,  0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,  0, 0, 0, 0, 0 },
        /*step*/                   { 1,  5,  1 },
        /*units*/                  { "ug/Nml", "l/h", "min" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_TIME },
        /*secondSelectionVisible*/ { false, false, false },
        /*delayIndicatorTime*/     { 0, 0, 0 },
        /*selectAvailable*/        { true, true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { setMaxFlow, setMaxTime, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[INSUFFLATION_MODE]*/ {
        /*stepsNum*/                 3,
        /*mainIcon*/                 BITMAP_INSUFLACION_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    true,
        /*maxPressure*/              200,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_FLOW_00_ID, BITMAP_VOLUME_00_ID },
        /*minValue*/               { 3,  10, 100,  0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 50, 2000, 0, 0, 0, 0, 0 },
        /*defValue*/               { 2,  30, 1500, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,    0, 0, 0, 0, 0 },
        /*step*/                   { 1,  1,  10 },
        /*units*/                  { "ug/Nml", "l/h", "ml" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_VOLUME },
        /*secondSelectionVisible*/ { false, false, true },
        /*delayIndicatorTime*/     { 0, 0, 0 },
        /*selectAvailable*/        { true, true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { setMaxFlow, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[INSUFFLATION_R_MODE]*/ {
        /*stepsNum*/                 3,
        /*mainIcon*/                 BITMAP_RECTALINSUFFLATION_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    true,
        /*maxPressure*/              200,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_FLOW_00_ID, BITMAP_VOLUME_00_ID },
        /*minValue*/               { 1,  10, 100,  0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 50, 2000, 0, 0, 0, 0, 0 },
        /*defValue*/               { 2,  30, 1500, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,    0, 0, 0, 0, 0 },
        /*step*/                   { 1,  1,  10 },
        /*units*/                  { "ug/Nml", "l/h", "ml" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_VOLUME },
        /*secondSelectionVisible*/ { false, false, true },
        /*delayIndicatorTime*/     { 0, 0, 0 },
        /*selectAvailable*/        { true, true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { setMaxFlow, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[INSUFFLATION_V_MODE]*/ {
        /*stepsNum*/                 3,
        /*mainIcon*/                 BITMAP_VAGINALINSUFFLATION_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    true,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_FLOW_00_ID, BITMAP_TIME_00_ID },
        /*minValue*/               { 1,  10, 1,  0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 50, 20, 0, 0, 0, 0, 0 },
        /*defValue*/               { 2,  30, 3,  0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,  0, 0, 0, 0, 0 },
        /*step*/                   { 1,  1,  1 },
        /*units*/                  { "ug/Nml", "l/h", "min" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_TIME },
        /*secondSelectionVisible*/ { false, false, true },
        /*delayIndicatorTime*/     { 0, 0, 0 },
        /*selectAvailable*/        { true, true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { setMaxFlow, setMaxTime, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[MANUAL_MODE]*/ {
        /*stepsNum*/                 2,
        /*mainIcon*/                 BITMAP_MANUAL_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_FLOW_00_ID },
        /*minValue*/               { 1,  10, 0,  0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 50, 0,  0, 0, 0, 0, 0 },
        /*defValue*/               { 4,  20, 10, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,  0, 0, 0, 0, 0 },
        /*step*/                   { 1,  1 },
        /*units*/                  { "ug/Nml", "l/h" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_TIME },
        /*secondSelectionVisible*/ { false, false },
        /*delayIndicatorTime*/     { 0, 0 },
        /*selectAvailable*/        { true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { setMaxFlow, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[DENTAL_MODE]*/ {
        /*stepsNum*/                 3,
        /*mainIcon*/                 BITMAP_GUN_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              200,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_FLOW_00_ID, BITMAP_OVERPRESSURE_00_ID },
        /*minValue*/               { 1,  10, 1,   0,  0, 0, 0, 0 },
        /*maxValue*/               { 80, 50, 800, 0,  0, 0, 0, 0 },
        /*defValue*/               { 2,  20, 700, 10, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,   0,  0, 0, 0, 0 },
        /*step*/                   { 1,  1,  1 },
        /*units*/                  { "ug/Nml", "l/h", "mbar" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_PRESSURE, TTV_TIME },
        /*secondSelectionVisible*/ { false, false, false },
        /*delayIndicatorTime*/     { 0, 0, 0 },
        /*selectAvailable*/        { true, true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { setMaxFlow, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[VACUUM_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_VACUUM_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              -200,
        /*icon*/                   { BITMAP_TIME_00_ID },
        /*minValue*/               { 1,   0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 120, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 15,  0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,   0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "secs" },
        /*therapyTargetValue*/     { TTV_VACUUM_TIME },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { true },
		/*vacuumNeeded*/           { true },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[VACUUM_TIME_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_VACUUM_T_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              -200,
        /*icon*/                   { BITMAP_TIME_00_ID },
        /*minValue*/               { 1,   0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 120, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 15,  0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,   0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "secs" },
        /*therapyTargetValue*/     { TTV_VACUUM_TIME },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { true },
		/*vacuumNeeded*/           { true },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[VACUUM_PRESSURE_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_VACUUM_P_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              -800,
        /*icon*/                   { BITMAP_OVERPRESSURE_00_ID },
        /*minValue*/               { 1,   0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 600, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 200, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 1,   0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "mbar" },
        /*therapyTargetValue*/     { TTV_VACUUM_PRESSURE },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { true },
		/*vacuumNeeded*/           { true },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[BAG_MODE]*/ {
        /*stepsNum*/                 4,
        /*mainIcon*/                 BITMAP_BAG_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_VACUUM_T_01_ID, BITMAP_O3_00_ID, BITMAP_VOLUME_00_ID, BITMAP_TIME_00_ID },
        /*minValue*/               { 1,  1,  1,  1,  0,  0, 0, 0 },
        /*maxValue*/               { 30, 80, 10, 20, 0,  0, 0, 0 },
        /*defValue*/               { 10, 5,  2,  2,  50, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,  0,  0,  0, 0, 0 },
        /*step*/                   { 1,  1,  1,  1 },
        /*units*/                  { "secs", "ug/Nml", "l", "min" },
        /*therapyTargetValue*/     { TTV_VACUUM_TIME, TTV_CONCENTRATION, TTV_VOLUME, TTV_TIME, TTV_FLOW },
        /*secondSelectionVisible*/ { false, false, false, false },
        /*delayIndicatorTime*/     { 0, 0, 0, 0 },
        /*selectAvailable*/        { true, true, true, true },
		/*vacuumNeeded*/           { true },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[CLOSED_BAG_MODE]*/ {
        /*stepsNum*/                 4,
        /*mainIcon*/                 BITMAP_CLOSEDBAG_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_VACUUM_T_01_ID, BITMAP_O3_00_ID, BITMAP_VOLUME_00_ID, BITMAP_TIME_00_ID },
        /*minValue*/               { 1,  1,  1,  1,  0,  0, 0, 0 },
        /*maxValue*/               { 30, 80, 10, 20, 0,  0, 0, 0 },
        /*defValue*/               { 10, 5,  2,  2,  50, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,  0,  0,  0, 0, 0 },
        /*step*/                   { 1,  1,  1,  1 },
        /*units*/                  { "secs", "ug/Nml", "l", "min" },
        /*therapyTargetValue*/     { TTV_VACUUM_TIME, TTV_CONCENTRATION, TTV_VOLUME, TTV_TIME, TTV_FLOW },
        /*secondSelectionVisible*/ { false, false, false, false },
        /*delayIndicatorTime*/     { 0, 0, 0, 0 },
        /*selectAvailable*/        { true, true, true, true },
		/*vacuumNeeded*/           { true },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[OPEN_BAG_MODE]*/ {
        /*stepsNum*/                 4,
        /*mainIcon*/                 BITMAP_OPENBAG_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_FLOW_00_ID, BITMAP_TIME_00_ID, BITMAP_VACUUM_T_01_ID },
        /*minValue*/               { 1,  10, 1,  1,  0, 0, 0, 0 },
        /*maxValue*/               { 80, 50, 20, 30, 0, 0, 0, 0 },
        /*defValue*/               { 10, 15, 5,  10, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,  0,  0,  0, 0, 0, 0 },
        /*step*/                   { 1,  1,  1,  1 },
        /*units*/                  { "ug/Nml", "l/h", "min", "secs" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_FLOW, TTV_TIME, TTV_VACUUM_TIME },
        /*secondSelectionVisible*/ { false, false, false, false },
        /*delayIndicatorTime*/     { 0, 0, 0, 0 },
        /*selectAvailable*/        { true, true, true, true },
		/*vacuumNeeded*/           { true },
        /*okAction*/               { setMaxFlow, setMaxTime, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[DOSE_MODE]*/ {
        /*stepsNum*/                 2,
        /*mainIcon*/                 BITMAP_DOSE_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_DOSE_01_ID },
        /*minValue*/               { 1,  1,    0,  0, 0, 0, 0, 0 },
        /*maxValue*/               { 80, 5000, 0,  0, 0, 0, 0, 0 },
        /*defValue*/               { 20, 2000, 30, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0,    0,  0, 0, 0, 0, 0 },
        /*step*/                   { 1,  1 },
        /*units*/                  { "ug/Nml", "ug" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION, TTV_DOSE, TTV_FLOW },
        /*secondSelectionVisible*/ { false, false },
        /*delayIndicatorTime*/     { 0, 0 },
        /*selectAvailable*/        { true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[SALINE_MODE]*/ {
        /*stepsNum*/                 4,
        /*mainIcon*/                 BITMAP_SALINE_01_ID,
        /*endTotalDoseVisible*/      true,
        /*endTotalVolumeVisible*/    true,
        /*endTotalTimeVisible*/      true,
        /*okButtonVisible*/          true,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_VOLUME_00_ID, BITMAP_O3_00_ID, BITMAP_FLOW_00_ID, BITMAP_TIME_00_ID },
        /*minValue*/               { 1,     1,  10, 1,  0, 0, 0, 0 },
        /*maxValue*/               { 10000, 80, 50, 20, 0, 0, 0, 0 },
        /*defValue*/               { 2000,  15, 20, 10, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,     0,  0,  0,  0, 0, 0, 0 },
        /*step*/                   { 100,   1,  1,  1 },
        /*units*/                  { "ml", "ug/Nml", "l/h", "min" },
        /*therapyTargetValue*/     { TTV_VOLUME, TTV_CONCENTRATION, TTV_FLOW, TTV_TIME },
        /*secondSelectionVisible*/ { false, false, true, false },
        /*delayIndicatorTime*/     { 0, 0, 0, 0 },
        /*selectAvailable*/        { true, true, true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, setMaxFlow, setMaxTime, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[RFU_1_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              0,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 2, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[MAX_OPERATION_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              0,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 2, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[CAL_PRESS_MODE]*/ {
        /*stepsNum*/                 2,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              2000,
        /*icon*/                   { BITMAP_OVERPRESSURE_00_ID, BITMAP_OVERPRESSURE_00_ID },
        /*minValue*/               { 800,  1,    0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 1100, 5000, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 940,  2000, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,    0,    0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1,  10 },
        /*units*/                  { "P.Atm (mbar)", "500 mbar" },
        /*therapyTargetValue*/     { TTV_CALIBRATION_VAL_0, TTV_CALIBRATION_VAL_1 },
        /*secondSelectionVisible*/ { false, false },
        /*delayIndicatorTime*/     { 0, 0 },
        /*selectAvailable*/        { true, false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { CalibratePressureStep1, CalibratePressureStep2, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[CAL_FLOW_MODE]*/ {
        /*stepsNum*/                 2,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              2000,
        /*icon*/                   { BITMAP_FLOW_00_ID, BITMAP_FLOW_00_ID },
        /*minValue*/               { 500,  450, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 2000, 550, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 700,  500, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,    0,   0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1,  1 },
        /*units*/                  { "Fix 30 l/h", "External read (l/m)" },
        /*therapyTargetValue*/     { TTV_CALIBRATION_VAL_0, TTV_CALIBRATION_VAL_1 },
        /*secondSelectionVisible*/ { false, false },
        /*delayIndicatorTime*/     { 0, 0 },
        /*selectAvailable*/        { true, false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { CalibrateFlowStep1_Ok, CalibrateFlowStep2, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { CalibrateFlowStep1_Value, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[CAL_O3_MODE]*/ {
        /*stepsNum*/                 5,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              2000,
        /*icon*/                   { BITMAP_O3_00_ID, BITMAP_O3_00_ID, BITMAP_O3_00_ID, BITMAP_O3_00_ID, BITMAP_O3_00_ID },
        /*minValue*/               { 1, 1,    1, 1,    1,    0, 0, 0 },
        /*maxValue*/               { 3, 1023, 3, 1023, 1023, 0, 0, 0 },
        /*defValue*/               { 2, 350,  2, 50,   15,   0, 0, 0 },
        /*negativeValue*/          { 0, 0,    0, 0,    0,    0, 0, 0 },
        /*step*/                   { 1, 1,    1, 1,    1 },
        /*units*/                  { "60 ug/Nml","60 ug/Nml", "15 ug/Nml", "15 ug/Nml", "1 ug/Nml" },
        /*therapyTargetValue*/     { TTV_CALIBRATION_VAL_0, TTV_CALIBRATION_VAL_0, TTV_CALIBRATION_VAL_1, TTV_CALIBRATION_VAL_1, TTV_CALIBRATION_VAL_2 },
        /*secondSelectionVisible*/ { false, false, false },
        /*delayIndicatorTime*/     { 100000, 0, 12000, 0, 0 },
        /*delayIndicatorTime*/  /* { (GLB_fsm_o3.HwConfig.O3Sensor == NO_O3_SENSOR) ? 20000 : 110000, 0, 12000, 0, 0 },*/ // should be like this (implemented in run time)
        /*selectAvailable*/        { false, true, false, true, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, CalibrateO3_Ref_1_Ok, DelegateDummy, CalibrateO3_Ref_2_Ok, CalibrateO3_Ref_3_Ok, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, CalibrateO3_Ref_1_Value, DelegateDummy, CalibrateO3_Ref_2_Value, CalibrateO3_Ref_3_Value, DelegateDummy, DelegateDummy },
    },
#if 0
    /*[CAL_PFACTOR_MODE]*/ {
        /*stepsNum*/                 2,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              2000,
        /*icon*/                   { BITMAP_JERINGA_01_ID, BITMAP_JERINGA_01_ID },
        /*minValue*/               { 1, 1,  0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 3, 64, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 2, 32, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0,  0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1, 1 },
        /*units*/                  { "P Factor", "P Factor" },
        /*therapyTargetValue*/     { TTV_CALIBRATION_VAL_0, TTV_CALIBRATION_VAL_0 },
        /*secondSelectionVisible*/ { false, false, false },
        /*delayIndicatorTime*/     { 10000, 0 },
        /*selectAvailable*/        { false, true },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { CalibratePfactor_Ok, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { CalibratePfactor_Value, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
#endif
    /*[CAL_PERIOD_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 2, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 3000 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[GENERATION_TYPE_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 3, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[SAVE_PARAMS_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 4, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 5600 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[LOAD_PARAMS_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 5, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 37000 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[SW_VERSION_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 6, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[PRESSURE_TEMP_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 7, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[SHOW_PARAMS_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 8, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[SHOW_STARTUP_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 9, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1, 0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0, 0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    },
    /*[NO_MODE]*/ {
        /*stepsNum*/                 1,
        /*mainIcon*/                 BITMAP_SETTINGS_100_A_ID,
        /*endTotalDoseVisible*/      false,
        /*endTotalVolumeVisible*/    false,
        /*endTotalTimeVisible*/      false,
        /*okButtonVisible*/          false,
        /*bigPauseButtonVisible*/    false,
        /*maxPressure*/              700,
        /*icon*/                   { BITMAP_O3_00_ID },
        /*minValue*/               { 0,  0, 0, 0, 0, 0, 0, 0 },
        /*maxValue*/               { 10, 0, 0, 0, 0, 0, 0, 0 },
        /*defValue*/               { 1,  0, 0, 0, 0, 0, 0, 0 },
        /*negativeValue*/          { 0,  0, 0, 0, 0, 0, 0, 0 },
        /*step*/                   { 1 },
        /*units*/                  { "" },
        /*therapyTargetValue*/     { TTV_CONCENTRATION },
        /*secondSelectionVisible*/ { false },
        /*delayIndicatorTime*/     { 0 },
        /*selectAvailable*/        { false },
		/*vacuumNeeded*/           { false },
        /*okAction*/               { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
        /*sliderAction*/           { DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy, DelegateDummy },
    }
};

#endif /* APPLICATION_USER_TOUCHGFX_GUI_INCLUDE_GUI_MODEL_THERAPYTEMPLATES_HPP_ */
